steps:
 # 0 - Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_CLOUD_RUN_PROJECT-$BRANCH_NAME:$COMMIT_SHA', '.']
 # 1 - Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/$_CLOUD_RUN_PROJECT-$BRANCH_NAME:$COMMIT_SHA']
 # 2 - Deploy container image to Cloud Run 
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
    - 'run'
    - 'deploy'
    - '$_CLOUD_RUN_PROJECT'
    - '--image'
    - 'gcr.io/$PROJECT_ID/$_CLOUD_RUN_PROJECT-$BRANCH_NAME:$COMMIT_SHA'
    - '--region'
    - '$_CLOUD_RUN_REGION'
    - '--platform'
    - 'managed'
images:
 - 'gcr.io/$PROJECT_ID/$_CLOUD_RUN_PROJECT-$BRANCH_NAME:$COMMIT_SHA'